id: P010449
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG5994
  title: བཀའ་བསྡུ་བཞི་པའི་འགྲེལ་པ་ལུང་རིགས་གཏེར་མཛོད་ངེས་གསང་ཀུན་གསལ་ཐུབ་བསྟན་མཛེས་རྒྱན
  author: ''
  volumes:
    42ee4268bf6b475fa27f84e7595ae642:
      image_group_id: I1KG6020
      title: ''
      volume_number: 1
      total_pages: 314
      base_file: v001.txt
